name: CI

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Specify the Node.js version
      - name: Install dependencies
        run: |
          cd spez-frontend
          npm install


      - name: Build the project
        run: |
          cd spez-frontend
          npm run build --if-present

